cabal-version: 3.0
name: sc-tools-browser
version: 0.1.0.0
build-type: Simple
license: Apache-2.0

executable sc-tools-browser
  main-is: Main.hs
  other-modules: MatchingNumber PortChecks
  hs-source-dirs: .
  default-language: Haskell2010
  default-extensions: ImportQualifiedPost
  ghc-options: -O1 -rtsopts -with-rtsopts=-K64m
  build-depends:
    base, aeson, bytestring, base16-bytestring, text, containers, mtl, contra-tracer,
    cardano-api, convex-base, convex-coin-selection, convex-mockchain,
    convex-wallet, plutus-core, plutus-ledger-api, serialise
